version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: codesample
      MYSQL_USER: maxwell
      MYSQL_PASSWORD: maxwell
      MYSQL_ROOT_PASSWORD: maxwell
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - :33060:3306

  redis:
    image: redis
    ports:
      - 6379:6379
